package com.stadio.model.enu;

public enum ConfigKey {

    FIRE_BASE_API,
    MAX_FAST_PRACTICE,
    PRICE_FAST_PRACTICE,
    MODE_PAYMENT,
    MODE_PAYMENT_IOS,
    ANDROID_MIN_VERSION,
    ANDROID_CURRENT_VERSION,
    ANDROID_UPDATE_URL,
    IOS_MIN_VERSION,
    IOS_CURRENT_VERSION,
    IOS_UPDATE_URL,
    U_DATE_DEADLINE,
    FACEBOOK_GROUP,
    FACEBOOK_PAGE,
    FACEBOOK_MESSENGER,
    WEBSITE_URL,
    POLICY_URL,
    PRIVACY_URL,
    PURCHASE_URL,
    CMS_NAV_BAR,
    ALLOW_REGISTER,
    MOBILE_KEY_HEADER,
    MOBILE_IMAGE_DEFAULT,
    VIMEO_ACCESS_TOKEN
}
